add Page of component
js-tasks-ru/htmlcss-20220210_izoliya pull request #11
Opened 2022-03-23 03:41 UTC by OlesyaLuka

2022-03-23 03:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-23 10:36 UTC, GSemikozov requested changes

2022-03-23 10:36 UTC, GSemikozov commented on components/component/component.css
> +.component {
слишком абстрактное имя) я бы рекомендовал назвать этот блок например .component-page хотя бы

2022-03-23 10:36 UTC, GSemikozov commented on components/component/component.css
> +.component__window {
__wrapper или __container

2022-03-23 10:36 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_component {
.footer_component_page

2022-03-23 10:36 UTC, GSemikozov commented on components/footer/footer.css
> +    .footer__text-component {
.footer_component_page .footer__text

2022-03-23 10:36 UTC, GSemikozov commented on components/header/header.css
> +.header_component {
.header_component_page

2022-03-23 10:36 UTC, GSemikozov commented on components/page/page.css
> +.page_component {
.page_component -> .page_component_page

и тут появилась другая идея: раз у нас есть блок .page, то для страницы компонента не надо использовать отдельный блок, а можно в контексте .page создать модификатор .page_component или .page_component_description. В общем, так тоже можно

2022-03-23 12:47 UTC, OlesyaLuka commented on components/component/component.css
> +.component {
Хорошо

2022-03-23 12:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-23 12:47 UTC, OlesyaLuka commented on components/component/component.css
> +.component__window {
Принято

2022-03-23 12:48 UTC, OlesyaLuka commented on components/footer/footer.css
> +.footer_component {
у всех сделала модификатор component_description

2022-03-23 12:49 UTC, OlesyaLuka commented on components/footer/footer.css
> +    .footer__text-component {
исправила. .footer__text_component_description

2022-03-23 12:49 UTC, OlesyaLuka commented on components/header/header.css
> +.header_component {
ок

2022-03-23 12:51 UTC, OlesyaLuka commented on components/page/page.css
> +.page_component {
т.е. можно было оставить везде, как первоначально было .page_component .footer_component .header_component ? Я исправила везде на _component_description - чтобы понятнее было,  о чем речь

2022-03-23 21:48 UTC, GSemikozov commented on components/page/page.css
> +.page_component {
не совсем - здесь речь больше о самом макро-компоненте .page и .component

2022-03-23 21:50 UTC, GSemikozov requested changes

2022-03-23 21:50 UTC, GSemikozov commented on components/component/component.css
> +.component__wrapper {
.component-page__wrapper?

2022-03-23 21:50 UTC, GSemikozov commented on components/component/component.css
> +.component__menu{
.component__menu -> .component-page__menu?

2022-03-23 21:50 UTC, GSemikozov commented on components/container/container.css
> +    height: 100%;
ой, вот это точно будет лишним)
да и width: 100% - поскольку блочный элемент и так растягивается на 100%)

2022-03-24 09:59 UTC, OlesyaLuka commented on components/component/component.css
> +.component__wrapper {
да, логично и понятнее

2022-03-24 09:59 UTC, OlesyaLuka commented on components/component/component.css
> +.component__menu{
ок

2022-03-24 10:00 UTC, OlesyaLuka commented on components/container/container.css
> +    height: 100%;
исправила

2022-03-24 10:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-24 11:17 UTC, GSemikozov approved these changes

2022-03-24 11:17 UTC, merged