add radio
js-tasks-ru/htmlcss-20220210_izoliya pull request #17
Opened 2022-04-11 16:40 UTC by OlesyaLuka

2022-04-11 16:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-13 20:56 UTC, GSemikozov requested changes

2022-04-13 20:56 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.section-choice {
лишняя штука затесалась в файле компонента

2022-04-14 03:33 UTC, OlesyaLuka commented on 07-lection5/02-radio/radio.css
> +.section-choice {
Ок. Были сомнения насчет этого, поэтому в других аналогичных заданиях не стала делать :)

2022-04-14 13:34 UTC, GSemikozov approved these changes

2022-04-14 13:34 UTC, merged