add page components - template and avatar
js-tasks-ru/htmlcss-20220210_izoliya pull request #22
Opened 2022-04-25 10:44 UTC by OlesyaLuka

Доработала код Шаблона страницы компонентов. И сделала страницу аватара (после утверждения сделаю остальные)

2022-04-25 10:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-25 14:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-25 14:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-30 10:14 UTC, GSemikozov requested changes

2022-04-30 10:14 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar__preview_component {
.avatar_preview_component

2022-05-04 05:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-04 05:21 UTC, OlesyaLuka commented on 06-lection4/01-avatar/avatar.css
> +.avatar__preview_component {
Точно, это же модификатор. Исправила

2022-05-04 20:09 UTC, GSemikozov approved these changes

2022-05-04 20:09 UTC, merged