add dz-03. Кнопка
js-tasks-ru/htmlcss-20220210_izoliya pull request #3
Opened 2022-03-03 17:57 UTC by OlesyaLuka

2022-03-03 17:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-04 09:30 UTC, GSemikozov requested changes

2022-03-04 09:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 0px;
а все-таки внутренние отступы в кнопке нам нужны)
чтобы отодвинуть внутренний контент от границ кнопки; значения можно взять из макета

2022-03-04 09:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border: none;
если бордер появляется в alternate, тогда сразу лучше задать box-sizing: border-box

2022-03-04 09:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button {
не хватает стилей для оформления текста / шрифта

2022-03-04 09:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background-color 200ms ease-in-out;
транзишн можно задать 1 раз сразу на .button, чтобы не дублировать на каждом типе

2022-03-04 09:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
и курсор тоже можно 1 раз сразу на .button

2022-03-04 09:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
чтобы пользователь не мог нажать на такой элемент лучше задать pointer-events: none

2022-03-04 10:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-04 10:44 UTC, GSemikozov approved these changes

2022-03-04 10:44 UTC, merged