add dz-03-02 Аккордеон
js-tasks-ru/htmlcss-20220210_izoliya pull request #4
Opened 2022-03-05 11:46 UTC by OlesyaLuka

2022-03-05 11:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-05 19:39 UTC, GSemikozov requested changes

2022-03-05 19:39 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion * {
а вот универсального селектора лучше избегать)
можно оставить все как есть, просто убрать `*`

2022-03-05 19:39 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
ширину лучше жестко не фиксировать, на мобилке сразу будет плохо

2022-03-05 19:39 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item__summary {
получилось как будто бы элемент элемента)
это достаточно часто встречающаяся ошибка, советую еще разок пересмотреть статью которую я рекомендовал к прочтению, там об этом есть.
правильно было бы так: .accordion__summary

2022-03-05 19:39 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item__content {
.accordion__item-content или просто .accordion__content

2022-03-05 19:39 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details .accordion__item__summary {
сразу 3 ошибки: 1.  селектор тега вместо класса 2. вложенные селекторы без необходимости 3. элемент элемент судя по последнему классу
думаю, намек понят ;)

2022-03-05 19:39 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +details[open] .accordion__item__summary img {
details[open] .accordion__item__summary img ->> details[open] .accordion__item-arrow

2022-03-06 11:58 UTC, OlesyaLuka commented on 03-lection1/02-accordion/accordion.css
> +.accordion * {
почему-то не наследуются свойства шрифта потомками. Но я исправила. Добавила этот селектор нужным потомкам.

2022-03-06 11:58 UTC, OlesyaLuka commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
ок

2022-03-06 12:00 UTC, OlesyaLuka commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item__summary {
да, я видимо не до конца еще поняла эту тему, потому что были сложности, как сделать этот селектор. Думаю, что с практикой придет ясность

2022-03-06 12:00 UTC, OlesyaLuka commented on 03-lection1/02-accordion/accordion.css
> +.accordion__item__content {
ок, поняла

2022-03-06 12:02 UTC, OlesyaLuka commented on 03-lection1/02-accordion/accordion.css
> +details .accordion__item__summary {
я убрала эту конструкцию. содержимое селектора перенесла в .accordion__summary. Почему я вообще так сделала - для меня сейчас загадка.

2022-03-06 12:03 UTC, OlesyaLuka commented on 03-lection1/02-accordion/accordion.css
> +details[open] .accordion__item__summary img {
суть понятна :)

2022-03-06 12:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-06 14:42 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion * {
а это потому, что такая же ошибка есть и в main.css - там шрифт Roboto вешается через `*`, то есть на КАЖДЫЙ элемент)) поэтому надо поменять - ставить Roboto просто на body )

2022-03-06 15:26 UTC, OlesyaLuka commented on 03-lection1/02-accordion/accordion.css
> +.accordion * {
теперь понятно! Прям наглядный пример того, что селектор * надо использовать с осторожностью.

2022-03-06 15:31 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-06 19:29 UTC, GSemikozov approved these changes

2022-03-06 19:30 UTC, merged