add Modal
js-tasks-ru/htmlcss-20220210_izoliya pull request #9
Opened 2022-03-15 12:06 UTC by OlesyaLuka

2022-03-15 12:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-15 21:12 UTC, GSemikozov requested changes

2022-03-15 21:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
не нужно импортировать в компонент стили других компонентов, особенно с учетом того что они и так подключаются в main.css)

2022-03-15 21:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +p {
обязательно использовать класс

2022-03-15 21:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    top: 50%;
top: 0;
bottom: 0;
left: 0;
right: 0;
background-color: rgba(196, 196, 196, 0.6);

это должно быть указано здесь)

2022-03-15 21:12 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    top: 50%;
а центрирование самого окна, наоборот, в .modal__window

2022-03-16 02:02 UTC, OlesyaLuka commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
т.е. я правильно понимаю, что делаю импорт компонентов в в файле main.css?

2022-03-16 03:04 UTC, OlesyaLuka commented on 05-lection3/02-modal/modal.css
> +    top: 50%;
не понимаю, почему.
.modal__window - это полупрозрачная обложка, которая занимает весь экран,
.modal - это модалка, которую надо отцентрировать.
Могу предположить, что тебя спутали названия классов, типа .modal должен быть подложкой. Переименовала их, чтобы визуально было легче воспринимать. Потому что если дело не в этом, то я в замешательстве и требуются детальные пояснения.

2022-03-16 03:11 UTC, OlesyaLuka commented on 05-lection3/02-modal/modal.css
> +p {
заработало! видимо, была ошибка, которую я не замечала

2022-03-16 03:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-16 16:27 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
да, надо это делать в каком-то одном месте - либо в указанном файле, либо в теге head хтмл-страницы

2022-03-16 16:29 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    top: 50%;
нет, наоборот))

блок не может быть ребенком своего собственного ребенка)) 

да, имена классов должны четко соответствовать БЭМ-методологии, чтобы всегда все было прозрачно.

2022-03-16 16:30 UTC, GSemikozov requested changes

2022-03-16 16:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
именно сам блок будет fixed

2022-03-16 16:30 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
а уже вложенные элементы можно и через absolute и через relative

2022-03-16 16:39 UTC, OlesyaLuka commented on 05-lection3/02-modal/modal.css
> +    top: 50%;
ок! БЭМ еще надо повторять :)

2022-03-16 16:40 UTC, OlesyaLuka commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
ок, поняла этот момент

2022-03-16 16:40 UTC, OlesyaLuka commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
ок

2022-03-16 17:01 UTC, OlesyaLuka commented on 05-lection3/02-modal/modal.css
> +@import '../../03-lection1/01-button/button.css';
ок

2022-03-16 18:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-16 19:03 UTC, GSemikozov approved these changes

2022-03-16 19:03 UTC, merged